### ISSUE TITLE
HTTP 2 IRC bridge 

### ISSUE THREAD

**Issue by jdmaturen** [collinvandyck/gesture#21]
Would be great if gesture could take a request over HTTP and then post the content to a channel. Then could do something like `arc paste ... | gesture #eng` as a one liner.

**Comment by jdmaturen** [comment]
This also implies a gesture client.

**Comment by ohlol** [comment]
just use irccat

**Comment by collinvandyck** [comment]
oh hey guise :wave:

**Comment by jdmaturen** [comment]
aloha!
