### ISSUE TITLE
Google image search plugin should query for link headers

### ISSUE THREAD

**Issue by collinvandyck** [collinvandyck/gesture#9]
Headers without a 200 response code should exclude that result from being sent back into the channel.

**Comment by jdmaturen** [comment]
Should also append ?lol.png if necessary

**Comment by collinvandyck** [comment]
f17c866d073d70b654541fe6fdda1ac1f26580e0 will filter out urls that don't have a 200 response code.

**Comment by collinvandyck** [comment]
Closed by https://github.com/collinvandyck/gesture/pull/10
